### PR TITLE
New event structure

### PR DESCRIPTION
**Pull request by benfoxall**
This now pulls the event data from a series of files in `/events/foo.md` 

Other than that, there's a bit of cleanup:
- ~~move node/gulp/npm stuff to a `./scripts` directory so there's less bumf and we know when the building might be broken~~ (reverted)
- made some steps toward aws/s3/cloudfront deployment which will be great when set up (keep the repo nice and clean and simple)
- a brief test of circle for deployment (switched back to travis for now)

### CODE REVIEW

**Comment by spikeheap** [comment]
This looks good. It seems like we're breaking convention and adding complexity by moving `package.json` into `scripts/`, though I can see the benefit of putting everything else in there. Could we move package.json back and just update the references? 

On the directory naming, jekyll uses `_site` for its output, so using `site` for our sources might be a bit confusing. Is it such a bad thing to have our source named `src` (or equivalent)?

**Comment by thisjunewest** [comment]
Agree with Ryan on all points, otherwise looks ace!

**Comment by benfoxall** [comment]
Cool.  The reason it's separated out is that I wanted to be able to run it in something like lambda - though I guess that's a hack for a different time.

**Comment by spikeheap** [comment]
👊👍🕶

**Pull request merged**
