### PR TITLE
Gulp

### PR DESCRIPTION
**Pull request by benfoxall**
I'm not sure if we need jekyll, or whatever.  Since we're using travis to build stuff for github pages, it seems to be less useful.

This changes stuff to a pretty minimal/sketchy gulp setup - so it's just [slightly more](https://github.com/jsoxford/summerofhacks.github.io/tree/gulp/src) than static html.

I've also plonked in the event text with the same font thing.  And there's an svg now.

### CODE REVIEW

**Comment by spikeheap** [comment]
- :+1: to Gulp over Grunt, and :+1: to simplification.
- :-1: to the font, that's horrendous!
- I intentionally used Bootstrap to lower the barrier to entry for contributors. We do want/need more content. Is it a good idea to make it more onerous to add more content/structure?
- :+1: for the favicon, much cleaner.

**Comment by tomlane** [comment]
> I intentionally used Bootstrap to lower the barrier to entry for contributors. We do want/need more content. Is it a good idea to make it more onerous to add more content/structure?

(Making wild assumptions that the intentions are "easy to contribute" vs "we're dragging all of bootstrap around for a small site")

Maybe there could be a middle ground here. If we're wanting to use Bootstrap while keeping the code clean would it be worth using the bower and uncss gulp tasks to bring in the less version of bootstrap and remove anything we aren't using in the build?

**Comment by spikeheap** [comment]
Hi @tomlane, that would work well – I'm not averse to a zero-library approach per-se, but we need to get the site up this asap (preferably this week), so I'm concerned that this is a regression from the previous grunt build (which was just nabbed from the JSOxford site) which lowers our chances of achieving this.

**Comment by benfoxall** [comment]
The font is the same one used in the logo! (also, it's awesome).

I've tweaked it a bit to be more like the logo one - uppercase and spaced out a bit so it matches the logo.

image

I don't think bootstrap lowers barrier to entry - though maybe means that there are fewer arguments about markup/approach.  What content are we thinking of putting on here?  I think it should be crazy minimal and link off to other sites - we don't want to be worrying about keeping content shared over meetup/jsoxford/summerofhacks.

**Comment by tomlane** [comment]
That looks really good. And yeah I think that was problem in the past keeping everything up to date? Could we reuse the meetup stuff in someway from jsoxford.com?

**Comment by spikeheap** [comment]
Re: the font. It does look good for the SoH logo, but there are some serious kerning issues when it's used elsewhere (see the spacing between the O and X of 'JSOxHack, the L and S of 'RailsBridge' and the A and C of 'SusHack'). We could make it less obvious by increasing the letter spacing, but it's not really suitable for other text.

I'm not bothered by Bootstrap, but I don't see a case for deliberately removing it as this PR does. It's fine if we're not adding much/any content to the site, but it means that anyone wanting to add in content in a responsive grid will need to reinvent the wheel (or include a grid library), and likewise for other components.

It's up for discussion, but I think this should be the central point for the summer of hacks. The content on Meetup.com is just to help people who've found it through that (and should be copied from and link to here). JSOxford.com pulls the events from Meetup anyway, so there's less to worry about there. This is where we're 'selling' SoH so minimal is good, but it needs to tell people: 
- what the event series is about
- what the events are, when they're on and what they need to bring
- what the code of conduct is 

Effectively it's the same as a conference website and should 'work' standalone. If we've just put it up to have a fancy logo and link to somewhere else then I don't really see the benefit of building this at all considering there's so much else to do for SoH. 

What does everyone else think?

@tomlane integrating it with Meetup and pre-rendering the avatars, etc. would be nice. As we're unlikely to update this site (or at least this year's event pages) once the events have happened I wouldn't recommend calling the API in-browser because in a few years time it almost certainly won't work, and it's nice to have a working site for posterity.

**Comment by benfoxall** [comment]
> Re: the font. It does look good for the SoH logo, but there are some serious kerning issues when it's used elsewhere (see the spacing between the O and X of 'JSOxHack, the L and S of 'RailsBridge' and the A and C of 'SusHack'). We could make it less obvious by increasing the letter spacing, but it's not really suitable for other text.

I'd agree that it's not really suitable for main copy - though if we can use it for the main headers; I think it's cool that it's consistent with the logo/brand.

> I'm not bothered by Bootstrap, but I don't see a case for deliberately removing it as this PR does. It's fine if we're not adding much/any content to the site, but it means that anyone wanting to add in content in a responsive grid will need to reinvent the wheel (or include a grid library), and likewise for other components.

This PR is to clean up/simplify stuff.  In the same way as jekyll & grunt are unnecessary - bootstrap doesn't really add anything to the site, in fact I'd say it over-complicates and bloats it. We could plonk it back in down the line if there would be use in it I guess.

> It's up for discussion, but I think this should be the central point for the summer of hacks. The content on Meetup.com is just to help people who've found it through that (and should be copied from and link to here). JSOxford.com pulls the events from Meetup anyway, so there's less to worry about there. This is where we're 'selling' SoH so minimal is good, but it needs to tell people:
> 
> what the event series is about
> what the events are, when they're on and what they need to bring
> what the code of conduct is
> Effectively it's the same as a conference website and should 'work' standalone. If we've just put it up to have a fancy logo and link to somewhere else then I don't really see the benefit of building this at all considering there's so much else to do for SoH.

Totally agree that it should say stuff about what the series is about, and having a common code of conduct is awesome.  But I _don't_ think this needs to be the source of all information - I see it as less of a conference site and more of a "digital week/festival" site.

I think it would be cooler to have a short description about the event and a link to the the meetup page for detailed and practical information.  Duplicating all the info on [sushack.co.uk](http://sushack.co.uk/) for example - seems like it would take a lot of work and not be that useful for attendees.  Also - pushing people to meetup for the other events makes it easier to ask questions.

> What does everyone else think?
> 
> @tomlane integrating it with Meetup and pre-rendering the avatars, etc. would be nice. As we're unlikely to update this site (or at least this year's event pages) once the events have happened I wouldn't recommend calling the API in-browser because in a few years time it almost certainly won't work, and it's nice to have a working site for posterity.

I don't think we should integrate with meetup - for the reasons I mentioned above, and also if we were to re-use expand down the line; it makes it a bit more open for other events.

**Comment by spikeheap** [comment]
In the interests of expediency, let's merge this. :+1:, assuming that font doesn't get used for body text (and if someone wanted to play around with spacing to see if it looks better a bit more spaced out that could be cool too).

:+1: to leaving meetup out for now. I think a gulp/grunt task which pulled the avatars/attendee list from Meetup.com would be great for posterity and to show momentum, but it's not critical to getting the site up. Also :+1: for the irony of pushing out all the JS as 'bloat' ;).

I quite liked the previous JSOxford setup where everything lived on the blog, though Meetup.com is very useful as a ticketing system. I'm pretty against using Meetup.com as our single point of truth for practical info for a variety of reasons, but primarily because GitHub (and markdown) is how we manage everything else, and it's a pain to trawl through previous events on Meetup looking for text to copy forward, but that's a discussion to be had somewhere else. 

I also think the 'effort' required to duplicate the information across both sites is being a _little_ bigged-up, but agree that duplication is generally a pain.

**Comment by benfoxall** [comment]
:+1:  :+1:  :+1:

**Pull request merged**
